### ISSUE TITLE
4장 우수 투표

### ISSUE THREAD

**Issue by chaenabi** [pg-server-study/spring-study#13]
4장에 정리 완료 확인 후에 가장 정리를 잘했다고 생각하는 분에게 태그와 함께 우수 투표해주세요 !

이슈 닫으시는 분이 README 수정 부탁드립니다.
main 브랜치의 BEST 닉네임이랑 링크 + 각자 링크 만 넣어주시면 됩니다 .

예시:
### Chapter4

**예외**

| 닉네임    | 정리                                                         |
| --------- | ------------------------------------------------------------ |
| BEST      | [@minnim6](minnim6의_   4장정리_URL) |
| pursue503 | [4장 - 예외](purse503의 _4장정리_URL)|
| minnim6   | [4장 - 예외](minnim6의   _4장정리_URL)|
| chaenabi   | [4장 - 예외](chaenabi의   _4장정리_URL)|

**Comment by pursue503** [comment]
@chaenabi  브랜치 이슈로 3장 브랜치에 같이 push 되었습니다.

**Comment by chaenabi** [comment]
@minnim6 #16 우수자료에 투표합니다. 고생하셨습니다. 락킹에 대한 추가자료 정리 감사드립니다.

**Comment by pursue503** [comment]
@minnim6 #16 우수 정리 자료에 투표합니다

**Comment by pursue503** [comment]
최종:  #16 @minnim6 님이 우수 정리
