### ISSUE TITLE
5장 정리 우수 투표

### ISSUE THREAD

**Issue by chaenabi** [pg-server-study/spring-study#17]
5장에 정리 완료 확인 후에 가장 정리를 잘했다고 생각하는 분에게 태그와 함께 우수 투표해주세요 !

이슈 닫으시는 분이 README 수정 부탁드립니다.
main 브랜치의 BEST 닉네임이랑 링크 + 각자 링크 만 넣어주시면 됩니다 .

예시:
### Chapter5

**서비스 추상화**

| 닉네임    | 정리                                                         |
| --------- | ------------------------------------------------------------ |
| BEST      | [) |
| pursue503 | [5장 - 서비스 추상화](purse503의 _5장정리_URL)|
| minnim6   | [5장 - 서비스 추상화](minnim6의   _5장정리_URL)|
| chaenabi   | [5장 - 서비스 추상화](chaenabi의   _5장정리_URL)|

**Comment by pursue503** [comment]
4장으로 되어있는 오타 수정하였습니다.

**Comment by minnim6** [comment]
@pursue503 님께 한 표 드립니다 : )

**Comment by chaenabi** [comment]
@pursue503 우수작 한표드립니다
