### ISSUE TITLE
6-1 장 AOP 정리 우수 투표 및 일정

### ISSUE THREAD

**Issue by pursue503** [pg-server-study/spring-study#21]
**6장은 내용이 길어서 2회차로 나눠서 진행할 예정입니다**

**401 ~ 512 페이지 까지 정리하고 그 다음주에 나머지를 정리하여 진행할 예정입니다**

---

6장에 정리 완료 확인 후에 가장 정리를 잘했다고 생각하는 분에게 태그와 함께 우수 투표해주세요 !

이슈 닫으시는 분이 README 수정 부탁드립니다.
main 브랜치의 BEST 닉네임이랑 링크 + 각자 링크 만 넣어주시면 됩니다 .

예시:
### Chapter6

**AOP**

| 닉네임    | 정리                                                         |
| --------- | ------------------------------------------------------------ |
| BEST      | [) |
| pursue503 | [6-1장 - AOP](purse503의 _6장정리_URL)|
| minnim6   | [6-1장 - AOP](minnim6의   _6장정리_URL)|
| chaenabi   | [6-1장 - AOP](chaenabi의   _6장정리_URL)|

**Comment by chaenabi** [comment]
감히 제 정리본에 우수투표 1표 행사하겠습니다

**Comment by pursue503** [comment]
@chaenabi 님의 정리를 우수 정리본으로 추천합니다
cgLib, 프록시 패턴 , 데코레이터 패턴 다이내믹 프록시

특히 스프링에서 사용하는 책에서는 나오지않은 cgLib 를 정리해주셔서 매우 인상깊었습니다.

**Comment by minnim6** [comment]
@chaenabi 님 우수 정리본으로 추천해드립니다 . 꼼꼼하게 없는 예제까지 작성해주셔서 이해하기 편했습니다 .

**Comment by pursue503** [comment]
@chaenabi 로 선정 👍

**Comment by chaenabi** [comment]
감사합니다
