### ISSUE TITLE
9장(9.3) 정리 우수투표

### ISSUE THREAD

**Issue by chaenabi** [pg-server-study/spring-study#25]
**6장은 내용이 길어서 2회차로 나눠서 진행할 예정입니다**

**레거시 설명(7장)와 스프링 소개(8장)을 제외합니다.**
**9장의 내용중에서도 중요하다고 판단된 9.3 내용만 정리할 예정입니다. **
**782 ~ 826 페이지 까지 정리하고 정리한 내용을 바탕으로 스터디를 진행할 예정입니다**

---

6장에 정리 완료 확인 후에 가장 정리를 잘했다고 생각하는 분에게 태그와 함께 우수 투표해주세요 !

이슈 닫으시는 분이 README 수정 부탁드립니다.
main 브랜치의 BEST 닉네임이랑 링크 + 각자 링크 만 넣어주시면 됩니다 .

예시:
### Chapter9

**AOP**

| 닉네임    | 정리                                                         |
| --------- | ------------------------------------------------------------ |
| BEST      | [) |
| pursue503 | [9-1장 - AOP](purse503의 _9장정리_URL)|
| minnim6   | [9-1장 - AOP](minnim6의   _9장정리_URL)|
| chaenabi   | [9-1장 - AOP](chaenabi의   _9장정리_URL)|

**Comment by chaenabi** [comment]
@pursue503님의 자료에 투표합니다.

**Comment by pursue503** [comment]
@chaenabi 님의 자료에 투표합니다
저는 책을 거의 그대로 옮겨쓴거지만
@chaenabi 님은 핵심 부분만 뽑아서 잘 정리하신거 같습니다.

**Comment by minnim6** [comment]
@chaenabi 님께 한표 드려요 !

**Comment by pursue503** [comment]
@chaenabi 👍
