### ISSUE TITLE
2장 테스트 완료 및 우수 투표

### ISSUE THREAD

**Issue by pursue503** [pg-server-study/spring-study#7]
각 완료된 PR을 연결시키고

정리 잘한 사람을 뽑습니다.

**Comment by minnim6** [comment]
@pursue503 님께 한표 ! 본인의 경험을 작성한 부분도 매우 좋았고 , 메소드 정리한 표를 보면서 정말 세세하게 잘 쓰셨다고 느꼈어요 : )
